POST http://localhost:3333/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 3",
    "price": 420
}

###
GET http://localhost:3333/products/734560fa-2b99-47b3-9f84-bb777c4c758e HTTP/1.1

###
PUT http://localhost:3333/products/734560fa-2b99-47b3-9f84-bb777c4c758e HTTP/1.1
Content-Type: application/json

{
    "name": "Product 1 Updated",
    "price": 240
}

###
DELETE http://localhost:3333/products/63be681b-7b52-40fe-a533-5cf585e88fae HTTP/1.1